import type {
  DocumentStorageService,
  StoredDocument,
  UploadDocumentInput,
} from './documentStorage'

export class BackblazeStoragePlaceholder implements DocumentStorageService {
  upload(input: UploadDocumentInput): Promise<StoredDocument> {
    const safeFileName = input.fileName.replace(/[^a-zA-Z0-9._-]/g, '_')
    return Promise.resolve({
      objectKey: `applications/${input.applicationId}/${crypto.randomUUID()}-${safeFileName}`,
      fileName: input.fileName,
      mimeType: input.mimeType,
      sizeBytes: input.sizeBytes,
      provider: 'backblaze-b2',
    })
  }

  createTemporaryDownloadUrl(): Promise<string> {
    return Promise.reject(
      new Error('Backblaze B2 downloads must be generated by a secure server API.'),
    )
  }
}
